### ISSUE TITLE
Display AI tutor's profile picture in chat UI

### ISSUE THREAD

**Issue by jo-elimu** [elimu-ai/soga#9]
Replace "MODEL" with "Nya", and include her profile picture.

![Image](https://github.com/elimu-ai/soga/assets/1451036/42bc7f0d-8999-4921-8d95-85aba77dd3fe)

**Comment by saharulik** [comment]
<img width="334" alt="Screenshot 2024-03-31 at 13 33 48" src="https://github.com/elimu-ai/soga/assets/67610831/70145d0a-7733-4366-810c-f51def05248f">
Here we are
